// blur-admin-modern/src/app/pages/profile/profile-modal.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'app-profile-modal',
  standalone: true,
  imports: [FormsModule],
  template: `
    <div class="modal-header">
      <button type="button" class="close" aria-label="Close" (click)="activeModal.dismiss()">
        <em class="ion-ios-close-empty sn-link-close"></em>
      </button>
      <h4 class="modal-title" id="myModalLabel">Add Account</h4>
    </div>
    <form>
      <div class="modal-body">
        <p>Paste a link to your profile into the box below</p>
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Link to Profile" [(ngModel)]="link" name="link">
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" (click)="ok()">Save changes</button>
      </div>
    </form>
  `,
})
export class ProfileModalComponent {
  link = '';

  constructor(public readonly activeModal: NgbActiveModal) {}

  ok(): void {
    this.activeModal.close(this.link);
  }
}

// src/app/react/pages/ProfileModal.jsx
/**
 * ProfileModal — React equivalent of ProfileModalCtrl + profileModal.html.
 *
 * Props:
 *   isOpen   — boolean controlling visibility
 *   onSave   — callback receiving the entered link string
 *   onClose  — callback to dismiss the modal
 */
import React, { useState, useEffect } from 'react';

export function ProfileModal({ isOpen, onSave, onClose }) {
  var [link, setLink] = useState('');

  useEffect(function () {
    if (isOpen) {
      setLink('');
    }
  }, [isOpen]);

  if (!isOpen) {
    return null;
  }

  function handleSave() {
    onSave(link);
  }

  function handleBackdropClick(e) {
    if (e.target === e.currentTarget) {
      onClose();
    }
  }

  return React.createElement('div', {
    className: 'modal',
    style: { display: 'block', backgroundColor: 'rgba(0,0,0,0.5)' },
    onClick: handleBackdropClick
  },
    React.createElement('div', { className: 'modal-dialog' },
      React.createElement('div', { className: 'modal-content' },
        React.createElement('div', { className: 'modal-header' },
          React.createElement('button', {
            type: 'button',
            className: 'close',
            onClick: onClose,
            'aria-label': 'Close'
          },
            React.createElement('em', { className: 'ion-ios-close-empty sn-link-close' })
          ),
          React.createElement('h4', { className: 'modal-title', id: 'myModalLabel' }, 'Add Account')
        ),
        React.createElement('form', { name: 'linkForm' },
          React.createElement('div', { className: 'modal-body' },
            React.createElement('p', null, 'Paste a link to your profile into the box below'),
            React.createElement('div', { className: 'form-group' },
              React.createElement('input', {
                type: 'text',
                className: 'form-control',
                placeholder: 'Link to Profile',
                value: link,
                onChange: function (e) { setLink(e.target.value); }
              })
            )
          ),
          React.createElement('div', { className: 'modal-footer' },
            React.createElement('button', {
              type: 'button',
              className: 'btn btn-primary',
              onClick: handleSave
            }, 'Save changes')
          )
        )
      )
    )
  );
}
